const USERS_COLLECTION_NAME = "users";
const FOLDERS_COLLECTION_NAME = "folders";
const FILES_COLLECTION_NAME = "files"; 
const USERSFOLDERS_COLLECTION_NAME = "usersFolders";
const FOLDERSFILES_COLLECTION_NAME = "foldersFiles"; 

module.exports = {
    USERS_COLLECTION_NAME,
    FOLDERS_COLLECTION_NAME,
    FILES_COLLECTION_NAME,
    USERSFOLDERS_COLLECTION_NAME,
    FOLDERSFILES_COLLECTION_NAME
}