module.exports = {
    USERS: "users",
    FOLDERS: "folders",
    FILES: "files",
    USER_FOLDERS: "user_folders",
    FOLDER_FILES: "folder_files",
    FOLDER_USERS: "folder_users",
    MODIFIED_ON: "modified_on",
    MODIFIED_BY_USER_ID: "modified_by_user_id",
    CREATED_ON: "created_on",
    CREATED_BY_USER_ID: "created_by_user_id",
    FOLDER_ID: "folder_id",
    FILE_ID: "file_id",
    USER_ID: "user_id",
    LINK: "link",
    IMAGE_URL: "image_url",
    TITLE: "title",
    DESCRIPTION: "description",
    SECRET: "secret",
    FAVICON: "favicon",
    SHARE_LINK: "share_link",
    EMOJI: "emoji",
    SHARING_IS_ENABLED: "sharing_is_enabled"
}