const USERS_COLLECTION_NAME = "users";
const FOLDERS_COLLECTION_NAME = "folders";
const FILES_COLLECTION_NAME = "files"; 
const USERSFOLDERS_COLLECTION_NAME = "usersFolders";
const FOLDERSFILES_COLLECTION_NAME = "foldersFiles"; 
const MODIFIEDON_FIELD = "modifiedOn";
const MODIFIEDBY_FIELD = "modifiedBy"; 
const CREATEDON_FIELD = "createdOn"; 
const CREATEDBY_FIELD = "createdBy"; 
const FOLDERID_FIELD = "folderID"; 
const FOLDERTITLE_FIELD = "folderTitle"; 
const FILEID_FIELD = "fileID"; 
const FILETITLE_FIELD = "fileTitle";
const USERID_FIELD = "userID"; 

module.exports = {
    USERS_COLLECTION_NAME,
    FOLDERS_COLLECTION_NAME,
    FILES_COLLECTION_NAME,
    USERSFOLDERS_COLLECTION_NAME,
    FOLDERSFILES_COLLECTION_NAME,
    MODIFIEDON_FIELD,
    MODIFIEDBY_FIELD,
    CREATEDON_FIELD,
    CREATEDBY_FIELD,
    FOLDERID_FIELD,
    FOLDERTITLE_FIELD,
    FILEID_FIELD,
    FILETITLE_FIELD,
    USERID_FIELD
}